apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    #trigger: ${#triggerResolvedArtifactByType("docker/image")["reference"]}
    version: ${#triggerResolvedArtifactByType("docker/image")["version"]}
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: ${#triggerResolvedArtifactByType("docker/image")["reference"]}
          name: ${parameters.Tag}
          ports:
          - containerPort: 8080
