apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-helm-guestbook
  labels:
    app: helm-guestbook
    release: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: guestbook
    spec:
      containers:
        - name: helm-guestbook
          image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
