apiVersion: v1
kind: Service
metadata:
  name: guestbook-helm-guestbook
  labels:
    app: helm-guestbook
    release: guestbook
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helm-guestbook
    release: guestbook
