apiVersion: v1
kind: Service
metadata:
  name: blue-green-helm-guestbook-preview
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    release: blue-green
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helm-guestbook
    release: blue-green
